package main

import (
	"encoding/json"
	"fmt"
	"golang.org/x/net/http2"
	"math/rand"
	"github.com/bxcodec/faker/v3"
	"github.com/go-resty/resty/v2"
	"github.com/mssola/user_agent"
	"log"
	"net/http"
	"time"

	// "go.zoe.im/surferua"
	// 	    "github.com/mileusna/useragent"
	"github.com/tidwall/gjson"
)

func main() {
	fmt.Println("vim-go")



	//create user
	createUser()

}

//noinspection SpellCheckingInspection
func randomStickyIP() string{
	rand.Seed(time.Now().UnixNano())

	min := 10001
	max := 29999
	randomPort := rand.Intn(max - min + 1) + min
	ipString := "***REMOVED***:***REMOVED***" + "@us.smartproxy.com:" + string(randomPort)
	return ipString
}
func createUser() {

	user := new(User)
	//set proxy
	user.auth.proxy = randomStickyIP()
	//noinspection SpellCheckingInspection
	ua := user_agent.New("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36")
	user.init()

	log.Println(ua.Bot())
	// userp := &user

}

func (user *User) init() {


	user.grabCloudflare()
	user.grabFingerprint()
	user.details.username = faker.Username()
	user.details.password = faker.Password()

}
func (user *User) genUserAgent() {
	//noinspection ALL
	agent := "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
	user.auth.userAgent = agent
	log.Println("Set useragent")
}

// func superProp(agent string) string {
// 	ua.Parse(agent)
// }
// func xTrack() string {

// }

func (user *User) register() {
	captcha := getCaptcha()
	realRegister := RegPayload{Fingerprint: user.auth.fingerprint, Email: user.details.email, Username: user.details.username, Password: user.details.password, Invite: nil, Consent: true, GiftCodeSkuID: nil, CAPTCHAKey: captcha}
	registerURL := "https://discordapp.com/api/v6/auth/register"
	client := user.client
	resp, err := client.R().
		SetBody(realRegister).
		SetHeaders(map[string]string{
			"Accept":          "*/*",
			"Accept-Language": "en-US,en;q=0.5",
			"DNT":             "1",
			"Connection":      "keep-alive",
			"Referer":         "https://discordapp.com/",
			"TE":              "Trailers",
		}).
		Post(registerURL)
	if err != nil {
		log.Println(err)
	}
	token := gjson.Get(resp.String(), "token").String()
	user.auth.token = token
	log.Println("set token in user to: ", token)

}
type Email struct {
	email string
}
func (user *User) GenEmail() string {
	client := user.client
	client.SetProxy(user.auth.proxy)
	_, err := client.R().
		SetBody(`{"min_name_length": 10,"max_name_length": 10}`).
		SetHeaders(map[string]string{
		"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0",
		"Accept": "application/json, text/plain, */*",
		  "Accept-Language": "en-US,en;q=0.5",
		  "Content-Type": "application/json;charset=utf-8",
		  "Origin": "https://temp-mail.io",
		  "Connection": "keep-alive",
		  "Referer": "https://temp-mail.io/en",
		  "TE": "Trailers",
		}).Options("https://api.internal.temp-mail.io/api/v2/email/new")
	if err != nil {
		log.Print(err)
	}
	secondRequest, err := client.R().
		SetBody(`{"min_name_length": 10,"max_name_length": 10}`).
		SetHeaders(map[string]string{
		"Accept": "application/json, text/plain, */*",
	    "Referer": "https://temp-mail.io/en",
	    "Origin": "https://temp-mail.io",
	    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
	    "DNT": "1",
	    "Sec-Fetch-Mode": "cors",
	    "Content-Type": "application/json;charset=UTF-8",
		}).Post("https://api.internal.temp-mail.io/api/v2/email/new")
	var newEmail Email
	json.Unmarshal(secondRequest.Body(), &newEmail)
	log.Print(user.details.email)
	user.details.email = newEmail.email
	return user.details.email






}
// Generated by https://quicktype.io

// RegPayload The payload used to register the account.
type RegPayload struct {
	Fingerprint   string      `json:"fingerprint"`
	Email         string      `json:"email"`
	Username      string      `json:"username"`
	Password      string      `json:"password"`
	Invite        interface{} `json:"invite"`
	Consent       bool        `json:"consent"`
	GiftCodeSkuID interface{} `json:"gift_code_sku_id"`
	CAPTCHAKey    string      `json:"captcha_key"`
}

type auth struct {
	fingerprint, cfuid, userAgent, token, superProp, proxy string
	cookies []*http.Cookie
	OpenMsg OpenMsg
}

type userDetails struct {
	username, password, email string
}

// User Struct that defines the user
type User struct {
	details userDetails
	auth    auth
	client  *resty.Client
}
